### PR TITLE
allow `module.exports`

### LINKED ISSUE #6: not compatible with commonjs
This module won't lint itself for example ([this line](https://github.com/jhusain/eslint-plugin-immutable/blob/master/index.js#L3))

I don't see a way to use this in node or with a commonjs module bundler, since exporting a module is basically mutating the `module` or `exports` object. There seems to be no way around that.

``` js
// not allowed because they are mutating
modules.exports = 'foo'
exports.foo = 'bar'

// does not export anything at all
exports = 'bar' 
```

Disabling one rule in every module, on just one line, also seems like a dirty solution.

Maybe I'm missing something.

### PR DESCRIPTION
**Pull request by despairblue**
fixes #6

### CODE REVIEW

**Comment by despairblue** [comment]
meh. Just a sec, still trying to figure out how to work with tabs :confused:

**Comment by despairblue** [comment]
done

**Comment by ljharb** [comment]
This would probably be good to add test cases for.

**Comment by despairblue** [comment]
@ljharb absolutely, but what to use for testing? Mocha, Jasmine, Ava, Tape, or something else? I'd prefer Ava or Tape, but in the end the repo owner has to decide.

/cc @jhusain

**Comment by ljharb** [comment]
Since this isn't even on npm yet, my guess would be you could just make a choice and see what their reaction is :-)

**Comment by dtinth** [comment]
Usually, an ESLint plugin test is written using `RuleTester`.

http://eslint.org/docs/developer-guide/working-with-plugins#testing

**Pull request merged**
